from enum import Enum

from antlr4 import *
from antlr4.InputStream import InputStream
from antlr4.error.ErrorListener import ErrorListener
from antlr4.error.Errors import ParseCancellationException
from antlr4.tree.Tree import TerminalNodeImpl
from pydot import Dot, Edge, Node
from dist.qlangLexer import qlangLexer
from dist.qlangParser import qlangParser
from dist.qlangListener import qlangListener
from dist.qlangVisitor import qlangVisitor


def build_parser(stream: InputStream) -> qlangParser:
    """
    Build parser object generated by antlr
    :param text:
    :return:
    """
    lexer = qlangLexer(stream)
    lexer.removeErrorListeners()
    lexer.addErrorListener(RaisingErrorListener.INSTANCE)
    stream = CommonTokenStream(lexer)
    return qlangParser(stream)

def parse_stream(stream: InputStream, rule_name: str = "program"):
    parser = build_parser(stream)
    parser.removeErrorListeners()
    parser.addErrorListener(RaisingErrorListener.INSTANCE)
    fun = getattr(parser, rule_name)
    result = fun()
    return result


class InputType(Enum):
    TEXT = 1
    FILE = 2
    STDIN = 3

def parse(
    input_string: str = None,
    rule_name: str = "program",
    input_type: InputType = InputType.TEXT,
    encoding: str = "utf-8"):

    if input_type is InputType.TEXT:
        stream = InputStream(input_string)
    elif input_type is InputType.FILE:
        stream = FileStream(input_string, encoding=encoding)
    else:
        stream = StdinStream(encoding=encoding)

    return parse_stream(stream, rule_name)


def validate_program(program: str) -> bool:
    """
    Checks whether program is valid
    :param program:
    :return:
    """
    parser = build_parser(InputStream(program))
    parser.program()
    if parser.getNumberOfSyntaxErrors() == 0:
        return True
    else:
        return False



class SyntaxTreeVisitor(qlangVisitor):
    def __init__(self, text: str):
        parser = build_parser(InputStream(text))
        self.ast = parser.program()
        if parser.getNumberOfSyntaxErrors() != 0:
            raise ParseCancellationException("Not valid program")

        self.tree = Dot("tree", graph_type="digraph")
        self.number_nodes = 0
        self.nodes = {}
        self.rules = qlangParser.ruleNames
        super(qlangVisitor, self).__init__()

    def save_in_dot(self, path: str):
        ParseTreeWalker().walk(self, self.ast)
        self.tree.write(str(path))

    def enterEveryRule(self, rule: ParserRuleContext):
        if rule not in self.nodes:
            self.number_nodes += 1
            self.nodes[rule] = self.number_nodes
        if rule.parentCtx:
            self.tree.add_edge(Edge(self.nodes[rule.parentCtx], self.nodes[rule]))
        label = self.rules[rule.getRuleIndex()]
        self.tree.add_node(Node(self.nodes[rule], label=label))

    def exitEveryRule(self, rule: ParserRuleContext):
        pass



class RecognitionError(ValueError):
    def __init__(self, **kwargs):
        super().__init__(kwargs)
        self.values = kwargs


class RaisingErrorListener(ErrorListener):

    INSTANCE = None

    def syntaxError(self, recognizer, offendingSymbol, line, column, msg, e):
        raise RecognitionError(
            recognizer=recognizer,
            offendingSymbol=offendingSymbol,
            line=line,
            column=column,
            msg=msg,
            e=e,
        )

RaisingErrorListener.INSTANCE = RaisingErrorListener()