name: Run tests

on:
  [ push, pull_request ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install java and run antlr
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
        run: java -jar .\antlr-4.12.0-complete.jar -Dlanguage=Python3 project/qlang.g4 -visitor -o dist

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -f tests -v

